DECLARE @IDAgeTUC int = 21295
DECLARE @IDAgeTUCSUBE int = 10007630

DECLARE @IDAgeCBA int = 30
DECLARE @IDAgeCBASUBE int = 10007705

--EN ELDAR: CREAR UNA NUEVA AGENCIA CON EL MISMO NOMBRE QUE LA SUCURSAR AGREGANDO AL FINAL LA PALABRA "SUBE"
Select * from [192.168.5.2].Produccion2.dbo.Agencia WHERE Nombre LIKE '%CBA CAB%'  or Nombre LIKE '%tuc CAB%' order by Nombre

--EN FUSION: AGREGAR UN REGISTRO EN LA TABLA CLIENTE (HAY QUE ACTUALIZAR LA TABLA LSDatPrimaryKey)
select * from Cliente where IDCliente in(124,294) --CLIENTE VIRTUAL
select * from Cliente where IDCliente in(381,382) --CLIENTE SUBE

--EN FUSION AGREGAR UN NUEVO REGISTRO EN TABLA CtaCteCliente (HAY QUE ACTUALIZAR LA TABLA LSDatPrimaryKey)
SELECT * FROM CtaCteCliente WHERE IDCliente in(381,382)

--EN FUSION: AGREGAR EN TABLA AgenciaXCliente EL IDCLIENTE NUEVO CON LA MISMA AGENCIA PRINCIPAL O SEA LA DE VIRTUAL (HAY QUE ACTUALIZAR LA TABLA LSDatPrimaryKey)
sELECT * FROM Agencia where Nombre like 'roca%' or nombre like '%cabrera%'
SELECT TOP 100 *  FROM AgenciaXCliente WHERE IDAgencia in(21295)
SELECT TOP 100 *  FROM AgenciaXCliente WHERE IDCliente in(381,382)

--EN FUSION: AGREGAR EN TABLA AsignacionLimiteCredito UN REGISTRO CON EL CLIENTE DE SUBE Y EN EL CAMPO IDAGENCIA CLIENTE VA EL IDAGENCIA DE LA AGENCIA SUBE Y EL IDCLIENTE SUBE
SELECT TOP 100 * FROM AsignacionLimiteCredito  WHERE IDCliente in(381,382)

--EN FUSION: AGREGAR (O MODIFICAR SI YA ESTA EL IDCLIENTE DEL VIRTUAL) EN TABLA ClienteRelacionado EL IDCLIENTE DE VIRTUAL CON EL IDCLIENTE DE SUBE (HAY QUE ACTUALIZAR LA TABLA LSDatPrimaryKey)
SELECT TOP 100 * FROM ClienteRelacionado WHERE IDCliente in(231,280) -- ROCA
SELECT TOP 100 * FROM ClienteRelacionado WHERE IDCliente in(124,294) -- TUCUMAN

--EN FUSION: AGREGAR UN PRIMER MOVIMIENTO EN TABLA CtaCteMovimientoCliente
SELECT TOP 10 * FROM CtaCteMovimientoCliente WHERE IDCtaCteCliente IN(100712) ORDER BY Fecha

--EN FUSION: AGREGAR EN TABLA ListaPrecios UN REGISTRO PARA LA LISTA DE PRECIOS DEL NUEVO CLIENTE DE SUBE - EN IDAGENCIA VA EL MISMO IDAGENCIA QUE EL VIRTUAL
SELECT TOP 10 * FROM ListaPrecios WHERE IDAgencia IN (21295) --TUCUMAN

--EN FUSION: AGREGAR EN TABLA ListaPreciosDetalle UN REGISTRO CON EL IDListaPrecios GENERADO EN EL PASO ANTERIOR, ES UN SOLO REGISTRO DEL PRODUCTO SUBE
SELECT TOP 10 * FROM ListaPreciosDetalle WHERE IDListaPrecios  = 509

--si todo funciona verificar la solicitud en tabla AsignacionesEldarPendientes
Select TOP 10 * from AsignacionesEldarPendientes order by Fecha DESC

--------CASO CORDOBA Y TUCUMAN PARA EL USO DE FUSION Y EL MANEJO DE LAS CUENTAS CORRIENTES, EMITIR PAGOS ETC
--PARA QUE APAREZCAN LOS CLIENTES EN POSWEB6333 EN EMITIR PAGOS LAS AGENCIAS DEBEN SER HIJAS DE LA SUCURSAL Y HAY QUE TILDAR EL CAMPO "EsClienteInterno" y borrar la cache de Redis *ComboHijosAgenciasRutas:idagencia*
--Select * from [192.168.5.2].Produccion2.dbo.Agencia WHERE IDAgencia in (16771,15517) --hijos de Cordoba
--PARA QUE APAREZCAN EL LISTADO COMPLETO DE TODAS LAS AGENCIAS HIJA DE LOS HIJOS DE LA SUCURSAL EN EL CASO DE TUCUMAN Y CORDOBA MODIFIQUE EN LA CLASE PagosMasivosController
--LA LINEA 38 Y 70 if (AgeLog == 21295 || AgeLog == 30)
--EN LA PANTALLA EMITIR PAGOS CUANDO SE SELECCIONA UNA RUTA Y LUEGO EL PRODUCTO SUBE EL LISTADO DE PDVS SIEMPRE VA A SER MENOR QUE EL DE VIRTUAL, ESO ES PORQUE NO TIENEN MOVIMIENTOS EN LA TABLA FinancieroMovimientosSUBE

--PARA MOCO GRANDE
--SELECT        TOP (200) IDCtaCteMovimientoCliente, IDCtaCteCliente, Fecha, Importe, Saldo, TipoMovimiento, Observaciones, Activo, IDCajaConcepto, EsGastoNuevaAdm, IDAgencia, Usuario, FechaImputacion
--FROM            CtaCteMovimientoCliente
--WHERE        (IDCtaCteCliente = 100634)
--ORDER BY Fecha DESC